chore(demo): bug in google_fonts causing compile error
Bug in google_fonts causing compilation error of example & widgetbook
`Error: Type 'FontFeature' not found.`